#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run type check
npm run typecheck

# Run tests
npm test -- --bail --findRelatedTests --passWithNoTests

# Run lint if available
npm run lint --if-present
